### ISSUE TITLE
[BUG] Crash while riding dragon under water

### ISSUE THREAD

**Issue by St11l** [Wyrmheart-Team/Dragon_Mounts_Remastered#3]
When riding dragon under or close water on my local dedicated server then sever is crushing with error. In singleplayer game all work fine I think.

Game version 1.21.1
Server and client version NeoForge 21.1.65
Addon version 1.2.3

```
java.lang.IllegalStateException: Cannot get config value before config is loaded.
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar%2383!/:?] {}
	at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1234) ~[neoforge-21.1.72-universal.jar%23130!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1221) ~[neoforge-21.1.72-universal.jar%23130!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/dmr@1.2.2/dmr.DragonMounts.server.entity.DMRDragonEntity.getRiddenInput(DMRDragonEntity.java:520) ~[Dragon%20Mounts%20Remastered-1.21.1-1.2.2.jar%23131!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.travelRidden(LivingEntity.java:2291) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dmr.mixins.json:PlayerBreathMixin from mod dmr,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2755) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dmr.mixins.json:PlayerBreathMixin from mod dmr,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.aiStep(Mob.java:559) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:128) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/dmr@1.2.2/dmr.DragonMounts.server.entity.DMRDragonEntity.aiStep(DMRDragonEntity.java:454) ~[Dragon%20Mounts%20Remastered-1.21.1-1.2.2.jar%23131!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dmr.mixins.json:PlayerBreathMixin from mod dmr,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.tick(Mob.java:351) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/dmr@1.2.2/dmr.DragonMounts.server.entity.DMRDragonEntity.tick(DMRDragonEntity.java:396) ~[Dragon%20Mounts%20Remastered-1.21.1-1.2.2.jar%23131!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}
```

**Comment by GregX0** [comment]
Got the same problem, when the Dragon went into Water. Dedicated Server in Mod Pack BMC5 v9.5 with NeoForge:

`java.lang.IllegalStateException: Cannot get config value before config is loaded.
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1234)
	at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1221)
	at TRANSFORMER/dmr@1.2.3/dmr.DragonMounts.server.entity.DMRDragonEntity.getRiddenInput(DMRDragonEntity.java:520)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.travelRidden(LivingEntity.java:2291)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2755)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.aiStep(Mob.java:559)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:128)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:55)
	at TRANSFORMER/dmr@1.2.3/dmr.DragonMounts.server.entity.DMRDragonEntity.aiStep(DMRDragonEntity.java:454)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.tick(Mob.java:351)
	at TRANSFORMER/dmr@1.2.3/dmr.DragonMounts.server.entity.DMRDragonEntity.tick(DMRDragonEntity.java:396)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$173(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.wrapOperation$bda000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:6318)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`
